# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-26 00:02
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191225_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
